---
Name: catalog-manager
After: 'framework/*','cms/*'
---

Page:
  extensions:
    - CategoryPageHierarchyExtension

SiteConfig:
  required_permission:
    - SITETREE_VIEW_ALL
    - SITETREE_EDIT_ALL
